exports.MAX_FIRST_NAME_LENGTH = 50;
exports.MIN_FIRST_NAME_LENGTH = 3;
exports.MAX_LAST_NAME_LENGTH = 50;
exports.MIN_LAST_NAME_LENGTH = 3;
exports.MAX_PASSWORD_LENGTH = 50;
exports.MIN_PASSWORD_LENGTH = 8;
exports.EMAIL_DOMAIN = '@wolox';
exports.SALT_ROUNDS = 10;
